targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          create_to_json: true
        generate_for:
          include:
            - lib/features/**/models/*.dart
            - lib/features/**/*.dart
