name: fftcg_companion
description: A Final Fantasy TCG companion app for card management and collection tracking.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4
  firebase_app_check: ^0.3.2
  firebase_storage: ^12.4.4

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Routing
  go_router: ^14.8.1

  # Local Storage
  hive_ce: 2.10.1
  hive_ce_flutter: 2.2.0

  # Authentication
  google_sign_in: ^6.3.0

  # UI Components
  flex_color_scheme: ^8.1.1
  flex_color_picker: ^3.7.0
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  flutter_svg: ^2.0.17
  shimmer: ^3.0.0
  fl_chart: ^0.70.2
  flutter_native_splash: ^2.4.5

  # Utils
  dart_mappable: ^4.2.1 # Added
  intl: ^0.20.2
  collection: ^1.19.1
  talker: ^4.6.14
  talker_flutter: ^4.6.14
  talker_riverpod_logger: ^4.6.14
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.3
  image_picker: ^1.1.2
  csv: ^6.0.0
  google_fonts: ^6.2.1
  crypto: ^3.0.6
  flutter_html: ^3.0.0
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  dart_mappable_builder: ^4.2.1 # Added
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

  # Testing
  mocktail: ^1.0.4

  # Development Tools
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/elements/
    - assets/images/description/
    - assets/images/google_branding/
    - assets/images/google_branding/signin-assets/

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/images/logo_transparent_black.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo_transparent_splash.png
  color_dark: "#000000"
  image_dark: assets/images/logo_transparent_splash.png
  android_12:
    # For Android 12, we're using the approach without an icon background
    # The image should be 1152×1152 pixels, and fit within a circle 768 pixels in diameter
    color: "#000000"
    image: assets/images/logo_transparent_splash.png
    color_dark: "#000000"
    image_dark: assets/images/logo_transparent_splash.png
  ios: true
  web: false
  android: true
  fullscreen: false
  android_gravity: center
  ios_content_mode: center
